# Generated by Django 6.0.6 on 2026-07-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tipo_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('paypal', 'PayPal'), ('credito', 'Crédito (cuotas)')], max_length=15, null=True, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('paypal', 'PayPal'), ('credito', 'Crédito (cuotas)')], max_length=15),
        ),
    ]
