# Generated by Django 6.0.6 on 2026-07-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_estado_invoice_saldo_invoice_tipo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='iva_tarifa_0',
            field=models.BooleanField(default=False, verbose_name='Tarifa 0% de IVA'),
        ),
    ]
