# Generated by Django 6.0.6 on 2026-07-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_brand_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'permissions': [('mark_paid_invoice', 'Puede marcar facturas como pagadas'), ('charge_invoice_paypal', 'Puede cobrar facturas con PayPal'), ('view_iva_report', 'Puede ver el reporte de IVA')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
