# Generated by Django 6.0.6 on 2026-07-10 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0005_invoice_estado_invoice_saldo_invoice_tipo_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('FIRMADO', 'Firmado'), ('RECIBIDO', 'Recibido'), ('AUTORIZADO', 'Autorizado'), ('DEVUELTO', 'Devuelto')], default='GENERADO', max_length=12)),
                ('ambiente', models.CharField(default='1', help_text='1=Pruebas, 2=Producción', max_length=1)),
                ('clave_acceso', models.CharField(blank=True, max_length=49)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=49)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('xml_generado', models.TextField(blank=True, help_text='XML firmado (simulado)')),
                ('xml_autorizado', models.TextField(blank=True, help_text='XML dentro de la respuesta de autorización')),
                ('mensajes', models.TextField(blank=True, help_text='Bitácora de las respuestas simuladas del SRI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Comprobante electrónico',
                'verbose_name_plural': 'Comprobantes electrónicos',
                'ordering': ['-created_at'],
            },
        ),
    ]
