# Generated by Django 6.0.6 on 2026-07-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_electronica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobanteelectronico',
            options={'ordering': ['-created_at'], 'permissions': [('send_comprobanteelectronico', 'Puede enviar comprobantes al SRI')], 'verbose_name': 'Comprobante electrónico', 'verbose_name_plural': 'Comprobantes electrónicos'},
        ),
    ]
