# Generated by Django 6.0.6 on 2026-07-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersecurityprofile',
            options={'verbose_name': 'Perfil de seguridad de usuario', 'verbose_name_plural': 'Perfiles de seguridad de usuario'},
        ),
    ]
