# Generated by Django 6.0.6 on 2026-07-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_customer_dni'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('supplier', 'document_number'), name='unique_supplier_document_number'),
        ),
    ]
