# Generated by Django 6.0.6 on 2026-07-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchase_estado_purchase_saldo_purchase_tipo_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='purchasedetail',
            options={'verbose_name': 'Detalle de compra', 'verbose_name_plural': 'Detalles de compra'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='document_number',
            field=models.CharField(max_length=20, verbose_name='N.º de factura del proveedor'),
        ),
    ]
