# Generated by Django 6.0.6 on 2026-07-17 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_purchase_options_alter_purchasedetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'permissions': [('view_purchase_report', 'Puede ver el reporte de costo promedio')], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
