# Generated by Django 6.0.6 on 2026-07-10 14:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0005_invoice_estado_invoice_saldo_invoice_tipo_pago_and_more'),
        ('purchasing', '0002_purchase_estado_purchase_saldo_purchase_tipo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=15)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='purchasing.purchase')),
            ],
            options={
                'ordering': ['compra_id', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='CuotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=15)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='billing.invoice')),
            ],
            options={
                'ordering': ['factura_id', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuotaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('observacion', models.TextField(blank=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='creditos_ventas.cuotacompra')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('observacion', models.TextField(blank=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='creditos_ventas.cuotaventa')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuotacompra',
            constraint=models.UniqueConstraint(fields=('compra', 'numero'), name='unique_cuota_compra_numero'),
        ),
        migrations.AddConstraint(
            model_name='cuotaventa',
            constraint=models.UniqueConstraint(fields=('factura', 'numero'), name='unique_cuota_venta_numero'),
        ),
    ]
